# Generated by Django 4.1.1 on 2022-09-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='languagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('iso_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='votesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('ip', models.TextField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
