# Generated by Django 4.1.1 on 2022-09-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagesmodel',
            name='name',
            field=models.TextField(max_length=200),
        ),
    ]
